apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: gcr.io/moonlit-autumn-141913/grafana:v1
      imagePullSecrets:
      - name: myregistrykey
