apiVersion: v1
kind: Service
metadata:
  name: influxdb 
  labels:
    app: influxdb
spec:
  type: NodePort
  ports:
  - name: web
    port: 8083
    nodePort: 30004
  - name: api
    port: 8086
    nodePort: 30005
  selector:
    app: influxdb
